// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjr3dP5EgInOAk_UUdTCepLyLoDicjLR0',
    appId: '1:527209106729:web:9e21f11e9ef5a41d77fb38',
    messagingSenderId: '527209106729',
    projectId: 'acm22-4859c',
    authDomain: 'acm22-4859c.firebaseapp.com',
    storageBucket: 'acm22-4859c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjPaGm7H-otn5I3rbhd13PQWLcYWe7DTU',
    appId: '1:527209106729:android:9378bb5f0248ba5677fb38',
    messagingSenderId: '527209106729',
    projectId: 'acm22-4859c',
    storageBucket: 'acm22-4859c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjUHecw1-pU0XWYByn_XlJ5fxfOAoPTAk',
    appId: '1:527209106729:ios:0d44a0375ea64c8e77fb38',
    messagingSenderId: '527209106729',
    projectId: 'acm22-4859c',
    storageBucket: 'acm22-4859c.appspot.com',
    androidClientId: '527209106729-d1qvv6hp3eujbnon5v6k8vb9ck0gsl21.apps.googleusercontent.com',
    iosClientId: '527209106729-9kk4s30nr1i7fbkboeprg86tf2u1d776.apps.googleusercontent.com',
    iosBundleId: 'com.hellocom.acm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjUHecw1-pU0XWYByn_XlJ5fxfOAoPTAk',
    appId: '1:527209106729:ios:0d44a0375ea64c8e77fb38',
    messagingSenderId: '527209106729',
    projectId: 'acm22-4859c',
    storageBucket: 'acm22-4859c.appspot.com',
    androidClientId: '527209106729-d1qvv6hp3eujbnon5v6k8vb9ck0gsl21.apps.googleusercontent.com',
    iosClientId: '527209106729-9kk4s30nr1i7fbkboeprg86tf2u1d776.apps.googleusercontent.com',
    iosBundleId: 'com.hellocom.acm',
  );
}
